#!/bin/sh

TEST_NAME=$1;

export NOVAS_FSDB_FILE=trace.fsdb

if [ -x build/obj/Vtop ] ; then
   echo "build/obj/Vtop $* +verbose_mesh +verbosity=UVM_FULL +DEFAULT_LOG_LEVEL=1 +verbosity=UVM_FULL +EMU_LOG_LEVEL=1 -licwait 5 +verbositySC_SB=HIGH +verbosityNEIGH_SB=HIGH +l $TEST_NAME=1 +verbosityMINION_SB=HIGH +PRINT_EMU_DEBUG=1 +CHECKER=1" > run.log
   build/obj/Vtop $* +verbose_mesh +verbosity=UVM_FULL +DEFAULT_LOG_LEVEL=1 +verbosity=UVM_FULL +EMU_LOG_LEVEL=1 -licwait 5 +verbositySC_SB=HIGH +verbosityNEIGH_SB=HIGH +l $TEST_NAME=1 +verbosityMINION_SB=HIGH +PRINT_EMU_DEBUG=1 +CHECKER=1 |& tee -a run.log
else 
   echo "build/obj/Vtop is not build yet. Please execute ./rebuild"
fi
